services:
  web:
    platform: linux/amd64 
    build: 
      context: .
      dockerfile: app.Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    networks:
      - nt-coaching-infra
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      RAILS_MASTER_KEY: 96fd70b0bca008d00f9db205cb8f2a3f
      REDIS_URL: redis://redis:6379/0

  frontend:
    platform: linux/amd64
    build:
      context: ./frontend
      dockerfile: app.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app          # Only mount frontend code
      - /app/node_modules        # Persist node_modules (prevent host override)
    working_dir: /app
    command: yarn dev
    networks:
      - nt-coaching-infra
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3000

  sidekiq:
    platform: linux/amd64 
    build: 
      context: .
      dockerfile: app.Dockerfile
    command: bundle exec sidekiq
    networks:
      - nt-coaching-infra
    volumes:
      - .:/app
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      RAILS_MASTER_KEY: 96fd70b0bca008d00f9db205cb8f2a3f
      REDIS_URL: redis://redis:6379/0
      

volumes:
  postgres_data:

networks:
  nt-coaching-infra:
    name: nt-coaching-infra
    external: true